stages:
  - e2e

e2e-tests:
  tags:
    - mac

  stage: e2e

  before_script:
    - export PATH="$HOME/.nvm/versions/node/v18.20.8/bin:$PATH"
    - node -v
    - yarn -v
    - yarn install
    - npx playwright install

  script:
    - yarn run e2e

  artifacts:
    when: always

    reports:
      junit:
        - test-results/results.xml

    paths:
      - playwright-report/
      - test-results/

    expire_in: 1 week
