image: node:24

stages:
  - e2e

e2e-tests:
  stage: e2e

  before_script:
    - yarn install
    - npx playwright install --with-deps

  script:
    - yarn run e2e

  artifacts:
    when: always

    reports:
      junit:
        - test-results/results.xml

    paths:
      - playwright-report/
      - test-results/

    expire_in: 1 week